package userGUI;

import people.Administrator;

public class AdminGUI extends javax.swing.JFrame 
{
    private String userID;
    private Administrator thisUser;
    private Mode currentMode;
    private enum Mode
    {
        BEGINNING,
        REMOVEADMINACCOUNT,
        CREATEADMINACCOUNT,
        CREATEDOCTOR,
        REMOVEDOCTOR,
        CREATESECRETARY,
        REMOVESECRETARY,
        GIVEDOCTORFEEDBACK
    }
    /**
     * Creates new form AdminGUI
     */
    public AdminGUI(String userID) 
    {
        //this.userID = userID;
        thisUser = new Administrator(userID);
        initComponents();
        
        setMode(Mode.BEGINNING);
        sendUserMessage("Hello " + thisUser.getGivenName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel pnlMajorButtons = new javax.swing.JPanel();
        btnCreateAdminAccount = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        btnRemoveDoctor = new javax.swing.JButton();
        btnCreateSecretary = new javax.swing.JButton();
        btnRemoveSecretary = new javax.swing.JButton();
        btnRemoveAdminAccount = new javax.swing.JButton();
        btnGiveDoctorFeedback = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUserMassages = new javax.swing.JTextArea();
        jPanelListingPanel = new javax.swing.JPanel();
        pnlUserViewingPane = new javax.swing.JPanel();
        lblDisplay01 = new javax.swing.JLabel();
        lblDisplay02 = new javax.swing.JLabel();
        lblDisplay03 = new javax.swing.JLabel();
        lblDisplay04 = new javax.swing.JLabel();
        lblDisplay05 = new javax.swing.JLabel();
        lblDisplay06 = new javax.swing.JLabel();
        lblDisplay07 = new javax.swing.JLabel();
        lblDisplay08 = new javax.swing.JLabel();
        lblDisplay09 = new javax.swing.JLabel();
        lblDisplay10 = new javax.swing.JLabel();
        btnDisplaySelect01 = new javax.swing.JButton();
        btnDisplaySelect02 = new javax.swing.JButton();
        btnDisplaySelect03 = new javax.swing.JButton();
        btnDisplaySelect04 = new javax.swing.JButton();
        btnDisplaySelect05 = new javax.swing.JButton();
        btnDisplaySelect06 = new javax.swing.JButton();
        btnDisplaySelect07 = new javax.swing.JButton();
        btnDisplaySelect08 = new javax.swing.JButton();
        btnDisplaySelect09 = new javax.swing.JButton();
        btnDisplaySelect10 = new javax.swing.JButton();
        btnDisplaySelect14 = new javax.swing.JButton();
        btnDisplaySelect13 = new javax.swing.JButton();
        btnDisplaySelect12 = new javax.swing.JButton();
        btnDisplaySelect11 = new javax.swing.JButton();
        lblDisplay11 = new javax.swing.JLabel();
        lblDisplay12 = new javax.swing.JLabel();
        lblDisplay13 = new javax.swing.JLabel();
        lblDisplay14 = new javax.swing.JLabel();
        pnlEnterData = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        LblGivenName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblAddressLine1 = new javax.swing.JLabel();
        lblAddressLine3 = new javax.swing.JLabel();
        lblAddressLine2 = new javax.swing.JLabel();
        lblPostCode = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jTextFieldGivenName = new javax.swing.JTextField();
        jTextFieldAdd1 = new javax.swing.JTextField();
        jTextFieldAdd2 = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jTextFieldSurname = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextFieldPostCode = new javax.swing.JTextField();
        jTextFieldAdd3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateAdminAccount.setText("create Admin Account");
        btnCreateAdminAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminAccountActionPerformed(evt);
            }
        });

        btnCreateDoctor.setText("create Doctor");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        btnRemoveDoctor.setText("remove Doctor");
        btnRemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDoctorActionPerformed(evt);
            }
        });

        btnCreateSecretary.setText("create Secretary");
        btnCreateSecretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSecretaryActionPerformed(evt);
            }
        });

        btnRemoveSecretary.setText("remove Secretary");
        btnRemoveSecretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSecretaryActionPerformed(evt);
            }
        });

        btnRemoveAdminAccount.setText("remove Admin Account");
        btnRemoveAdminAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAdminAccountActionPerformed(evt);
            }
        });

        btnGiveDoctorFeedback.setText("give Doctor Feedback");
        btnGiveDoctorFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveDoctorFeedbackActionPerformed(evt);
            }
        });

        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jTextAreaUserMassages.setColumns(20);
        jTextAreaUserMassages.setRows(5);
        jScrollPane1.setViewportView(jTextAreaUserMassages);

        javax.swing.GroupLayout pnlMajorButtonsLayout = new javax.swing.GroupLayout(pnlMajorButtons);
        pnlMajorButtons.setLayout(pnlMajorButtonsLayout);
        pnlMajorButtonsLayout.setHorizontalGroup(
            pnlMajorButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMajorButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMajorButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateDoctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveSecretary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiveDoctorFeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMajorButtonsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMajorButtonsLayout.setVerticalGroup(
            pnlMajorButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMajorButtonsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnRemoveAdminAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateAdminAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateSecretary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveSecretary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGiveDoctorFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelListingPanelLayout = new javax.swing.GroupLayout(jPanelListingPanel);
        jPanelListingPanel.setLayout(jPanelListingPanelLayout);
        jPanelListingPanelLayout.setHorizontalGroup(
            jPanelListingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelListingPanelLayout.setVerticalGroup(
            jPanelListingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlUserViewingPane.setBackground(new java.awt.Color(204, 204, 204));

        lblDisplay01.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay01.setText("jLabel1");
        lblDisplay01.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay02.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay02.setText("jLabel1");
        lblDisplay02.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay03.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay03.setText("jLabel1");
        lblDisplay03.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay04.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay04.setText("jLabel1");
        lblDisplay04.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay05.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay05.setText("jLabel1");
        lblDisplay05.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay06.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay06.setText("jLabel1");
        lblDisplay06.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay07.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay07.setText("jLabel1");
        lblDisplay07.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay08.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay08.setText("jLabel1");
        lblDisplay08.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay09.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay09.setText("jLabel1");
        lblDisplay09.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay10.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay10.setText("jLabel1");
        lblDisplay10.setPreferredSize(new java.awt.Dimension(130, 35));

        btnDisplaySelect01.setText("Select");
        btnDisplaySelect01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect01ActionPerformed(evt);
            }
        });

        btnDisplaySelect02.setText("Select");
        btnDisplaySelect02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect02ActionPerformed(evt);
            }
        });

        btnDisplaySelect03.setText("Select");
        btnDisplaySelect03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect03ActionPerformed(evt);
            }
        });

        btnDisplaySelect04.setText("Select");
        btnDisplaySelect04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect04ActionPerformed(evt);
            }
        });

        btnDisplaySelect05.setText("Select");
        btnDisplaySelect05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect05ActionPerformed(evt);
            }
        });

        btnDisplaySelect06.setText("Select");
        btnDisplaySelect06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect06ActionPerformed(evt);
            }
        });

        btnDisplaySelect07.setText("Select");
        btnDisplaySelect07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect07ActionPerformed(evt);
            }
        });

        btnDisplaySelect08.setText("Select");
        btnDisplaySelect08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect08ActionPerformed(evt);
            }
        });

        btnDisplaySelect09.setText("Select");
        btnDisplaySelect09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect09ActionPerformed(evt);
            }
        });

        btnDisplaySelect10.setText("Select");
        btnDisplaySelect10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect10ActionPerformed(evt);
            }
        });

        btnDisplaySelect14.setText("Select");
        btnDisplaySelect14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect14ActionPerformed(evt);
            }
        });

        btnDisplaySelect13.setText("Select");
        btnDisplaySelect13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect13ActionPerformed(evt);
            }
        });

        btnDisplaySelect12.setText("Select");
        btnDisplaySelect12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect12ActionPerformed(evt);
            }
        });

        btnDisplaySelect11.setText("Select");
        btnDisplaySelect11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplaySelect11ActionPerformed(evt);
            }
        });

        lblDisplay11.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay11.setText("jLabel1");
        lblDisplay11.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay12.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay12.setText("jLabel1");
        lblDisplay12.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay13.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay13.setText("jLabel1");
        lblDisplay13.setPreferredSize(new java.awt.Dimension(130, 35));

        lblDisplay14.setForeground(new java.awt.Color(255, 255, 255));
        lblDisplay14.setText("jLabel1");
        lblDisplay14.setPreferredSize(new java.awt.Dimension(130, 35));

        javax.swing.GroupLayout pnlUserViewingPaneLayout = new javax.swing.GroupLayout(pnlUserViewingPane);
        pnlUserViewingPane.setLayout(pnlUserViewingPaneLayout);
        pnlUserViewingPaneLayout.setHorizontalGroup(
            pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                        .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDisplay02, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay03, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay04, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay05, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDisplay06, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDisplay07, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserViewingPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDisplay08, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay09, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDisplay14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDisplaySelect02)
                            .addComponent(btnDisplaySelect03)
                            .addComponent(btnDisplaySelect04)
                            .addComponent(btnDisplaySelect05)
                            .addComponent(btnDisplaySelect06)
                            .addComponent(btnDisplaySelect08)
                            .addComponent(btnDisplaySelect09)
                            .addComponent(btnDisplaySelect10)
                            .addComponent(btnDisplaySelect14)
                            .addComponent(btnDisplaySelect13)
                            .addComponent(btnDisplaySelect12)
                            .addComponent(btnDisplaySelect11)
                            .addComponent(btnDisplaySelect07, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisplay01, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnDisplaySelect01)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserViewingPaneLayout.setVerticalGroup(
            pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserViewingPaneLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplay01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplaySelect01))
                .addGap(16, 16, 16)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect02)
                    .addComponent(lblDisplay02, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect03)
                    .addComponent(lblDisplay03, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect04)
                    .addComponent(lblDisplay04, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect05)
                    .addComponent(lblDisplay05, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect06)
                    .addComponent(lblDisplay06, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect07)
                    .addComponent(lblDisplay07, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect08)
                    .addComponent(lblDisplay08, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect09)
                    .addComponent(lblDisplay09, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplaySelect10)
                    .addComponent(lblDisplay10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplay11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplaySelect11))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplay12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplaySelect12))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplay13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplaySelect13))
                .addGap(12, 12, 12)
                .addGroup(pnlUserViewingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplay14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplaySelect14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEnterData.setBackground(new java.awt.Color(153, 153, 255));

        lblTitle.setText("Title");

        LblGivenName.setText("Given Name");

        lblSurname.setText("Surname");

        lblAddressLine1.setText("Address line 1");

        lblAddressLine3.setText("Address Line 3");

        lblAddressLine2.setText("Address Line 2");

        lblPostCode.setText("PostCode");

        lblDOB.setText("DOB");

        lblPassword.setText("Password");

        jTextFieldTitle.setText("jTextField1");

        jTextFieldGivenName.setText("jTextField1");

        jTextFieldAdd1.setText("jTextField1");

        jTextFieldAdd2.setText("jTextField1");

        jTextFieldPassword.setText("jTextField1");

        jTextFieldSurname.setText("jTextField1");

        jTextField7.setText("jTextField1");

        jTextFieldPostCode.setText("jTextField1");

        jTextFieldAdd3.setText("jTextField1");

        javax.swing.GroupLayout pnlEnterDataLayout = new javax.swing.GroupLayout(pnlEnterData);
        pnlEnterData.setLayout(pnlEnterDataLayout);
        pnlEnterDataLayout.setHorizontalGroup(
            pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnterDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitle))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(LblGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGivenName, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAdd3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(pnlEnterDataLayout.createSequentialGroup()
                        .addComponent(lblPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPostCode, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEnterDataLayout.setVerticalGroup(
            pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnterDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGivenName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMajorButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelListingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUserViewingPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEnterData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanelListingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(pnlMajorButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlUserViewingPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlEnterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveAdminAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAdminAccountActionPerformed
        setMode(Mode.REMOVEADMINACCOUNT);
        sendUserMessage("Removing Admin Account");
    }//GEN-LAST:event_btnRemoveAdminAccountActionPerformed

    private void btnCreateAdminAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminAccountActionPerformed
        setMode(Mode.CREATEADMINACCOUNT);
        sendUserMessage("Creating Admin Account");
    }//GEN-LAST:event_btnCreateAdminAccountActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        setMode(Mode.CREATEDOCTOR);
        sendUserMessage("Creating Doctor account");
    }//GEN-LAST:event_btnCreateDoctorActionPerformed

    private void btnRemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDoctorActionPerformed
        setMode(Mode.REMOVEDOCTOR);
        sendUserMessage("Removing Doctor account");
    }//GEN-LAST:event_btnRemoveDoctorActionPerformed

    private void btnCreateSecretaryActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_btnCreateSecretaryActionPerformed
        setMode(Mode.CREATESECRETARY);
        sendUserMessage("creating Secretary Account");
    }//GEN-LAST:event_btnCreateSecretaryActionPerformed

    private void btnRemoveSecretaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSecretaryActionPerformed
        setMode(Mode.REMOVESECRETARY);
        sendUserMessage("removing Secretary Account");
    }//GEN-LAST:event_btnRemoveSecretaryActionPerformed

    private void btnGiveDoctorFeedbackActionPerformed(java.awt.event.ActionEvent e) {//GEN-FIRST:event_btnGiveDoctorFeedbackActionPerformed
        setMode(Mode.GIVEDOCTORFEEDBACK);
        sendUserMessage("Give doctor feedback.\nPick the doctor.");
    }//GEN-LAST:event_btnGiveDoctorFeedbackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setMode(Mode.BEGINNING);
        sendUserMessage("ACTION CANCELLED");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDisplaySelect01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect01ActionPerformed
        btnDisplaySelectHandler(lblDisplay01.getText());
    }//GEN-LAST:event_btnDisplaySelect01ActionPerformed

    private void btnDisplaySelect02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect02ActionPerformed
        btnDisplaySelectHandler(lblDisplay02.getText());
    }//GEN-LAST:event_btnDisplaySelect02ActionPerformed

    private void btnDisplaySelect03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect03ActionPerformed
        btnDisplaySelectHandler(lblDisplay03.getText());
    }//GEN-LAST:event_btnDisplaySelect03ActionPerformed

    private void btnDisplaySelect04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect04ActionPerformed
        btnDisplaySelectHandler(lblDisplay04.getText());
    }//GEN-LAST:event_btnDisplaySelect04ActionPerformed

    private void btnDisplaySelect05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect05ActionPerformed
        btnDisplaySelectHandler(lblDisplay05.getText());
    }//GEN-LAST:event_btnDisplaySelect05ActionPerformed

    private void btnDisplaySelect06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect06ActionPerformed
        btnDisplaySelectHandler(lblDisplay06.getText());
    }//GEN-LAST:event_btnDisplaySelect06ActionPerformed

    private void btnDisplaySelect07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect07ActionPerformed
        btnDisplaySelectHandler(lblDisplay07.getText());
    }//GEN-LAST:event_btnDisplaySelect07ActionPerformed

    private void btnDisplaySelect08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect08ActionPerformed
        btnDisplaySelectHandler(lblDisplay08.getText());
    }//GEN-LAST:event_btnDisplaySelect08ActionPerformed

    private void btnDisplaySelect09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect09ActionPerformed
        btnDisplaySelectHandler(lblDisplay09.getText());
    }//GEN-LAST:event_btnDisplaySelect09ActionPerformed

    private void btnDisplaySelect10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect10ActionPerformed
        btnDisplaySelectHandler(lblDisplay10.getText());
    }//GEN-LAST:event_btnDisplaySelect10ActionPerformed

    private void btnDisplaySelect11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect11ActionPerformed
        btnDisplaySelectHandler(lblDisplay11.getText());
    }//GEN-LAST:event_btnDisplaySelect11ActionPerformed

    private void btnDisplaySelect12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect12ActionPerformed
        btnDisplaySelectHandler(lblDisplay12.getText());
    }//GEN-LAST:event_btnDisplaySelect12ActionPerformed

    private void btnDisplaySelect13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect13ActionPerformed
        btnDisplaySelectHandler(lblDisplay13.getText());
    }//GEN-LAST:event_btnDisplaySelect13ActionPerformed

    private void btnDisplaySelect14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplaySelect14ActionPerformed
        btnDisplaySelectHandler(lblDisplay14.getText());
    }//GEN-LAST:event_btnDisplaySelect14ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        manageConfirmButton();
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String userID) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI(userID).setVisible(true);
                
            }

//			
        });
    }
    private void manageConfirmButton()
    {
        String madeUserID = "";
        switch(currentMode)
        {
            case REMOVEADMINACCOUNT:
                break;
            case CREATEADMINACCOUNT:
                if(checkDataInputs())
                {
                    userID = thisUser.createAdministrator(jTextFieldTitle.getText(), 
                        jTextFieldGivenName.getText(), jTextFieldSurname.getText(), 
                        jTextFieldAdd1.getText(), jTextFieldAdd2.getText(), 
                        jTextFieldAdd3.getText(), jTextFieldPostCode.getText(), 
                        jTextField7.getText(), jTextFieldPostCode.getText());
                    sendUserMessage("created with the ID of " + madeUserID);
                    setMode(Mode.BEGINNING);
                }
                else
                {
                    sendUserMessage("Fill out all required boxes");
                }
                break;
            case CREATEDOCTOR:
                if(checkDataInputs()) 
                {
                    userID = thisUser.createDoctor
                (jTextFieldTitle.getText(), jTextFieldGivenName.getText(), 
                jTextFieldSurname.getText(), jTextFieldAdd1.getText(), 
                jTextFieldAdd2.getText(), jTextFieldAdd3.getText(), 
                jTextFieldPostCode.getText(), jTextField7.getText(), 
                jTextFieldPostCode.getText());
                sendUserMessage("created with the ID of " + madeUserID);
                setMode(Mode.BEGINNING);
                }
                else
                {
                    sendUserMessage("Fill out all required boxes");
                }
                break;
            case REMOVEDOCTOR:
                break;
            case CREATESECRETARY:
                if(checkDataInputs()) 
                {
                    userID = thisUser.createSecretary
                (jTextFieldTitle.getText(), jTextFieldGivenName.getText(), 
                jTextFieldSurname.getText(), jTextFieldAdd1.getText(), 
                jTextFieldAdd2.getText(), jTextFieldAdd3.getText(), 
                jTextFieldPostCode.getText(), jTextField7.getText(), 
                jTextFieldPostCode.getText());
                sendUserMessage("created with the ID of " + madeUserID);
                setMode(Mode.BEGINNING);
                }
                else
                {
                    sendUserMessage("Fill out all required boxes");
                }
                break;
            case REMOVESECRETARY:
                break;
            case GIVEDOCTORFEEDBACK:
                break;
            case BEGINNING:
                break;
        }
    }
    private boolean checkDataInputs()
    {
        boolean entered = !(jTextField7.getText()).isEmpty();
        if(entered) entered = !(jTextFieldAdd1.getText()).isEmpty();
        if(entered) entered = !(jTextFieldAdd2.getText()).isEmpty();
        if(entered) entered = !(jTextFieldAdd3.getText()).isEmpty();
        if(entered) entered = !(jTextFieldGivenName.getText()).isEmpty();
        if(entered) entered = !(jTextFieldPassword.getText()).isEmpty();
        if(entered) entered = !(jTextFieldPostCode.getText()).isEmpty();
        if(entered) entered = !(jTextFieldSurname.getText()).isEmpty();
        if(entered) entered = !(jTextFieldTitle.getText()).isEmpty();
        return entered;
    }
    private void btnDisplaySelectHandler(String text)
    {
        switch(currentMode)
        {
            case REMOVEADMINACCOUNT:
                thisUser.removeAdministrator(text);
                sendUserMessage("Administrator " + text + " deleted");
                setMode(Mode.BEGINNING);
                break;
            case CREATEADMINACCOUNT:
                
                break;
            case CREATEDOCTOR:
                
                break;
            case REMOVEDOCTOR:
                thisUser.removeDoctor(text);
                sendUserMessage("Doctor " + text + " deleted");
                setMode(Mode.BEGINNING);
                break;
            case CREATESECRETARY:
                
                break;
            case REMOVESECRETARY:
                thisUser.removeSecretary(text);
                sendUserMessage("Secretary " + text + " deleted");
                setMode(Mode.BEGINNING);
                break;
            case GIVEDOCTORFEEDBACK:
                thisUser.sendDoctorFeedback(text);
                sendUserMessage("feedback sent to doctor " + text);
                setMode(Mode.BEGINNING);
                break;
            case BEGINNING:
                break;
        }   
    }
    private void setMode(Mode mode)
    {
        currentMode = mode;
        switch(mode)
        {
            case REMOVEADMINACCOUNT:
                managePnlMajorButtons(1);
                pnlUserViewingPane.setVisible(true);
                userViewingPaneLablesAndButtonControl
                    (thisUser.viewAdmins(), true, "Select");
                break;
            case CREATEADMINACCOUNT:
                managePnlMajorButtons(2);
                managePnlEnterData(true);
                break;
            case CREATEDOCTOR:
                managePnlMajorButtons(3);
                managePnlEnterData(true);
                break;
            case REMOVEDOCTOR:
                managePnlMajorButtons(4);
                pnlUserViewingPane.setVisible(true);
                userViewingPaneLablesAndButtonControl
                    (thisUser.viewDoctors(), true, "Select");
                break;
            case CREATESECRETARY:
                managePnlMajorButtons(5);
                managePnlEnterData(true);
                break;
            case REMOVESECRETARY:
                managePnlMajorButtons(6);
                pnlUserViewingPane.setVisible(true);
                userViewingPaneLablesAndButtonControl
                    (thisUser.viewSecretaries(), true, "Select");
                break;
            case GIVEDOCTORFEEDBACK:
                managePnlMajorButtons(7);
                pnlUserViewingPane.setVisible(true);
                userViewingPaneLablesAndButtonControl
                    (thisUser.viewDoctors(), true, "Select");
                break;
            case BEGINNING:
                managePnlMajorButtons(0);
                pnlUserViewingPane.setVisible(false);
                setViewingPanelLable(false);
                pnlEnterData.setVisible(false);
                managePnlEnterData(false);
                break;
        }   
    }
    private void managePnlEnterData(boolean onOrOff)
    {
        pnlEnterData.setVisible(onOrOff);
        jTextField7.setText(null);
        jTextFieldAdd1.setText(null);
        jTextFieldAdd2.setText(null);
        jTextFieldAdd3.setText(null);
        jTextFieldGivenName.setText(null);
        jTextFieldPassword.setText(null);
        jTextFieldPostCode.setText(null);
        jTextFieldSurname.setText(null);
        jTextFieldTitle.setText(null);
    }
    private void managePnlMajorButtons(int selection)
    {
        switch(selection)
        {
            case -1:
            btnCreateAdminAccount.setEnabled(false);
            btnCreateDoctor.setEnabled(false);
            btnCreateSecretary.setEnabled(false);
            btnGiveDoctorFeedback.setEnabled(false);
            btnRemoveAdminAccount.setEnabled(false);
            btnRemoveDoctor.setEnabled(false);
            btnRemoveSecretary.setEnabled(false);
            break;
        case 0:
            btnCreateAdminAccount.setEnabled(true);
            btnCreateDoctor.setEnabled(true);
            btnCreateSecretary.setEnabled(true);
            btnGiveDoctorFeedback.setEnabled(true);
            btnRemoveAdminAccount.setEnabled(true);
            btnRemoveDoctor.setEnabled(true);
            btnRemoveSecretary.setEnabled(true);
            btnConfirm.setVisible(false);
            btnConfirm.setEnabled(false);
            btnCancel.setVisible(false);
            btnCancel.setEnabled(false);
            break;
        case 1:
            managePnlMajorButtons(-1);
            btnRemoveAdminAccount.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            break;
        case 2:
            managePnlMajorButtons(-1);
            btnCreateAdminAccount.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            btnConfirm.setVisible(true);
            btnConfirm.setEnabled(true);
            break;
        case 3:
            managePnlMajorButtons(-1);
            btnCreateDoctor.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            btnConfirm.setVisible(true);
            btnConfirm.setEnabled(true);
            break;
        case 4:
            managePnlMajorButtons(-1);
            btnRemoveDoctor.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            break;
        case 5:
            managePnlMajorButtons(-1);
            btnCreateSecretary.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            btnConfirm.setVisible(true);
            btnConfirm.setEnabled(true);
            break;
        case 6:
            managePnlMajorButtons(-1);
            btnRemoveSecretary.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            break;
        case 7:
            managePnlMajorButtons(-1);
            btnGiveDoctorFeedback.setEnabled(true);
            btnCancel.setVisible(true);
            btnCancel.setEnabled(true);
            break;
        }
    }
    private void setViewingPanelLable(boolean onOrOff)
    {
        btnDisplaySelect14.setVisible(onOrOff);
        lblDisplay14.setVisible(onOrOff);
        btnDisplaySelect13.setVisible(onOrOff);
        lblDisplay13.setVisible(onOrOff);
        btnDisplaySelect12.setVisible(onOrOff);
        lblDisplay12.setVisible(onOrOff);
        btnDisplaySelect11.setVisible(onOrOff);
        lblDisplay11.setVisible(onOrOff);
        btnDisplaySelect10.setVisible(onOrOff);
        lblDisplay10.setVisible(onOrOff);
        btnDisplaySelect09.setVisible(onOrOff);
        lblDisplay09.setVisible(onOrOff);
        btnDisplaySelect08.setVisible(onOrOff);
        lblDisplay08.setVisible(onOrOff);
        btnDisplaySelect07.setVisible(onOrOff);
        lblDisplay07.setVisible(onOrOff);
        btnDisplaySelect06.setVisible(onOrOff);
        lblDisplay06.setVisible(onOrOff);
        btnDisplaySelect05.setVisible(onOrOff);
        lblDisplay05.setVisible(onOrOff);
        btnDisplaySelect04.setVisible(onOrOff);
        lblDisplay04.setVisible(onOrOff);
        btnDisplaySelect03.setVisible(onOrOff);
        lblDisplay03.setVisible(onOrOff);
        btnDisplaySelect02.setVisible(onOrOff);
        lblDisplay02.setVisible(onOrOff);
        btnDisplaySelect01.setVisible(onOrOff);
        lblDisplay01.setVisible(onOrOff);
    }
    private void userViewingPaneLablesAndButtonControl
        (String[] array, boolean onOrOff, String btnText)
    {
        switch(array.length)
        {
            case 14:
                btnDisplaySelect14.setEnabled(onOrOff);
                btnDisplaySelect14.setText(btnText);
                lblDisplay14.setText(array[13]);
                btnDisplaySelect14.setVisible(onOrOff);
                lblDisplay14.setVisible(onOrOff);
            case 13:
                btnDisplaySelect13.setEnabled(onOrOff);
                btnDisplaySelect13.setText(btnText);
                lblDisplay13.setText(array[12]);
                btnDisplaySelect13.setVisible(onOrOff);;
                lblDisplay13.setVisible(onOrOff);
            case 12:
                btnDisplaySelect12.setEnabled(onOrOff);
                btnDisplaySelect12.setText(btnText);
                lblDisplay12.setText(array[11]);
                btnDisplaySelect12.setVisible(onOrOff);
                lblDisplay12.setVisible(onOrOff);
            case 11:
                btnDisplaySelect11.setEnabled(onOrOff);
                btnDisplaySelect11.setText(btnText);
                lblDisplay11.setText(array[10]);
                btnDisplaySelect11.setVisible(onOrOff);
                lblDisplay11.setVisible(onOrOff);
            case 10:
                btnDisplaySelect10.setEnabled(onOrOff);
                btnDisplaySelect10.setText(btnText);
                lblDisplay10.setText(array[9]);
                btnDisplaySelect10.setVisible(onOrOff);
                lblDisplay10.setVisible(onOrOff);
            case 9:
                btnDisplaySelect09.setEnabled(onOrOff);
                btnDisplaySelect09.setText(btnText);
                lblDisplay09.setText(array[8]);
                btnDisplaySelect09.setVisible(onOrOff);
                lblDisplay09.setVisible(onOrOff);
            case 8:
                btnDisplaySelect08.setEnabled(onOrOff);
                btnDisplaySelect08.setText(btnText);
                lblDisplay08.setText(array[7]);
                btnDisplaySelect08.setVisible(onOrOff);
                lblDisplay08.setVisible(onOrOff);
            case 7:
                btnDisplaySelect07.setEnabled(onOrOff);
                btnDisplaySelect07.setText(btnText);
                lblDisplay07.setText(array[6]);
                btnDisplaySelect07.setVisible(onOrOff);
                lblDisplay07.setVisible(onOrOff);
            case 6:
                btnDisplaySelect06.setEnabled(onOrOff);
                btnDisplaySelect06.setText(btnText);
                lblDisplay06.setText(array[5]);
                btnDisplaySelect06.setVisible(onOrOff);
                lblDisplay06.setVisible(onOrOff);
            case 5:
                btnDisplaySelect05.setEnabled(onOrOff);
                btnDisplaySelect05.setText(btnText);
                lblDisplay05.setText(array[4]);
                btnDisplaySelect05.setVisible(onOrOff);
                lblDisplay05.setVisible(onOrOff);
            case 4:
                btnDisplaySelect04.setEnabled(onOrOff);
                btnDisplaySelect04.setText(btnText);
                lblDisplay04.setText(array[3]);
                btnDisplaySelect04.setVisible(onOrOff);
                lblDisplay04.setVisible(onOrOff);
            case 3:
                btnDisplaySelect03.setEnabled(onOrOff);
                btnDisplaySelect03.setText(btnText);
                lblDisplay03.setText(array[2]);
                btnDisplaySelect03.setVisible(onOrOff);
                lblDisplay03.setVisible(onOrOff);
            case 2:
                btnDisplaySelect02.setEnabled(onOrOff);
                btnDisplaySelect02.setText(btnText);
                lblDisplay02.setText(array[1]);
                btnDisplaySelect02.setVisible(onOrOff);
                lblDisplay02.setVisible(onOrOff);
            case 1:
                btnDisplaySelect01.setEnabled(onOrOff);
                btnDisplaySelect01.setText(btnText);
                lblDisplay01.setText(array[0]);
                btnDisplaySelect01.setVisible(onOrOff);
                lblDisplay01.setVisible(onOrOff);
            default:
        }
    }
    private void sendUserMessage(String message)
    {
        String currentMessages = jTextAreaUserMassages.getText();
        jTextAreaUserMassages.setText(currentMessages + "\n" + message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblGivenName;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnCreateAdminAccount;
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreateSecretary;
    private javax.swing.JButton btnDisplaySelect01;
    private javax.swing.JButton btnDisplaySelect02;
    private javax.swing.JButton btnDisplaySelect03;
    private javax.swing.JButton btnDisplaySelect04;
    private javax.swing.JButton btnDisplaySelect05;
    private javax.swing.JButton btnDisplaySelect06;
    private javax.swing.JButton btnDisplaySelect07;
    private javax.swing.JButton btnDisplaySelect08;
    private javax.swing.JButton btnDisplaySelect09;
    private javax.swing.JButton btnDisplaySelect10;
    private javax.swing.JButton btnDisplaySelect11;
    private javax.swing.JButton btnDisplaySelect12;
    private javax.swing.JButton btnDisplaySelect13;
    private javax.swing.JButton btnDisplaySelect14;
    private javax.swing.JButton btnGiveDoctorFeedback;
    private javax.swing.JButton btnRemoveAdminAccount;
    private javax.swing.JButton btnRemoveDoctor;
    private javax.swing.JButton btnRemoveSecretary;
    private javax.swing.JPanel jPanelListingPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaUserMassages;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldAdd1;
    private javax.swing.JTextField jTextFieldAdd2;
    private javax.swing.JTextField jTextFieldAdd3;
    private javax.swing.JTextField jTextFieldGivenName;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldPostCode;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblAddressLine2;
    private javax.swing.JLabel lblAddressLine3;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDisplay01;
    private javax.swing.JLabel lblDisplay02;
    private javax.swing.JLabel lblDisplay03;
    private javax.swing.JLabel lblDisplay04;
    private javax.swing.JLabel lblDisplay05;
    private javax.swing.JLabel lblDisplay06;
    private javax.swing.JLabel lblDisplay07;
    private javax.swing.JLabel lblDisplay08;
    private javax.swing.JLabel lblDisplay09;
    private javax.swing.JLabel lblDisplay10;
    private javax.swing.JLabel lblDisplay11;
    private javax.swing.JLabel lblDisplay12;
    private javax.swing.JLabel lblDisplay13;
    private javax.swing.JLabel lblDisplay14;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPostCode;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlEnterData;
    private javax.swing.JPanel pnlUserViewingPane;
    // End of variables declaration//GEN-END:variables
}
